FROM golang:1.8

WORKDIR /go/src/eth
COPY eth/ .

RUN go-wrapper download   # "go get -d -v ./..."
RUN go-wrapper install    # "go install -v ./..."

CMD go-wrapper run client --host eth-server.ronic.co --port 8888